<?php return array(
    'root' => array(
        'name' => 'textpattern/textpattern',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => 'e2030759832971d523427fffca0d7c948d0c4ca0',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'netcarver/textile' => array(
            'pretty_version' => 'v4.0.0',
            'version' => '4.0.0.0',
            'reference' => '79b7d5102816ff017a940d8695a35d7f8db1e60a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../netcarver/textile',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v6.6.5',
            'version' => '6.6.5.0',
            'reference' => '8b6386d7417526d1ea4da9edb70b8352f7543627',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'textpattern/textpattern' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => 'e2030759832971d523427fffca0d7c948d0c4ca0',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
