<?php return array(
    'root' => array(
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../../',
        'aliases' => array(),
        'reference' => '74b7c6e5e0dc6c9a3b7cabb648c2b53e9acfdf19',
        'name' => 'textpattern/textpattern',
        'dev' => true,
    ),
    'versions' => array(
        'netcarver/textile' => array(
            'pretty_version' => 'v3.7.6',
            'version' => '3.7.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../netcarver/textile',
            'aliases' => array(),
            'reference' => '1846fd5aeace2a0dd57c4f770f693d12bcd7fa26',
            'dev_requirement' => false,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v6.5.1',
            'version' => '6.5.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'reference' => 'dd803df5ad7492e1b40637f7ebd258fee5ca7355',
            'dev_requirement' => false,
        ),
        'textpattern/textpattern' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../../',
            'aliases' => array(),
            'reference' => '74b7c6e5e0dc6c9a3b7cabb648c2b53e9acfdf19',
            'dev_requirement' => false,
        ),
    ),
);
