---
.travis.yml:
  includes:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.0" STRICT_VARIABLES="yes" ORDERING="random"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0" STRICT_VARIABLES="yes" ORDERING="random"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0" STRICT_VARIABLES="yes" ORDERING="random"
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes" ORDERING="random"
    allow_failures:
Gemfile:
  required:
    ':development, :unit_tests':
      - gem: rspec-puppet
        version: '~> 2.1'
      - gem: rspec-core
        version: '3.1.7'
      - gem: puppetlabs_spec_helper
      - gem: simplecov
      - gem: puppet_facts
      - gem: json
    ':system_tests':
      - gem: beaker-rspec
      - gem: serverspec
