fixtures:
  repositories:
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "apt":
      repo: "git://github.com/puppetlabs/puppetlabs-apt.git"
      branch: "1.8.x"
  symlinks:
    "mongodb": "#{source_dir}"
